Fix s2p_interp() function
capn-freako/PyBERT pull request #139
Opened 2023-12-01 08:34 UTC by JJendryka

When I've tried using touchstone file to describe the channel, I've encountered an issue where results were nonsensical.
I've tried to solve the issue on my end, but couldn't do anything that worked. Decided to look into PyBERT's code. It seems that inside [`interp_s2p()`](https://github.com/capn-freako/PyBERT/blob/master/src/pybert/utility.py#L1137) function, call to [`skrf.network.Network.interpolate`](https://scikit-rf.readthedocs.io/en/latest/api/generated/skrf.network.Network.interpolate.html) is done with frequency in GHz, whereas the library expects it to be in Hz. I've created a commit that solves this issue.

In case it is not an issue, I would like to ask for an explanation what I'm doing wrong. Thanks.

2023-12-07 14:09 UTC, JJendryka commented
Outputed version is:
```
$ python -c "import skrf as dut; print(dut.__version__)"
0.29.1
```

2023-12-09 14:54 UTC, jdpatt requested changes
Since this change requires scikit-rf of at least 0.29.0 or greater, can you update the [pyproject.toml dependency](https://github.com/capn-freako/PyBERT/blob/master/pyproject.toml#L21)? 

I also get a RunTimeWarning from scipy (a dependency of scikit-rf) from when opening pybert of an overflow with W10/Python 3.10.

2023-12-10 23:15 UTC, capn-freako commented
> I also get a RunTimeWarning from scipy (a dependency of scikit-rf) from when opening pybert of an overflow with W10/Python 3.10.

Do you mean that you get this when you update the `scikit-rf` package to >=0.29 and not with previous versions, or is this something orthogonal to the updated `scikit-rf` version requirement?

2023-12-11 00:09 UTC, jdpatt commented
> > I also get a RunTimeWarning from scipy (a dependency of scikit-rf) from when opening pybert of an overflow with W10/Python 3.10.
> 
> Do you mean that you get this when you update the `scikit-rf` package to >=0.29 and not with previous versions, or is this something orthogonal to the updated `scikit-rf` version requirement?

After updating the package locally to 0.30.0; I got this warning.  So something with the newer version vs. the 0.24.1 version.  Did either of you get this as well?

2023-12-11 11:40 UTC, capn-freako commented
> After updating the package locally to 0.30.0; I got this warning. So something with the newer version vs. the 0.24.1 version. Did either of you get this as well?

Is this what you're seeing?

> RuntimeWarning: overflow encountered in matmul cov_x = invR @ invR.T

I've been getting that since v0.26.
So, I don't think it's related to crossing the v0.29 "threshold".
I've been assuming it innocuous, because I haven't seen anything different or abnormal in _PyBERT_ since it started showing up.

2023-12-11 11:43 UTC, capn-freako commented
> Since this change requires scikit-rf of at least 0.29.0 or greater, can you update the [pyproject.toml dependency](https://github.com/capn-freako/PyBERT/blob/master/pyproject.toml#L21)?

@jdpatt , I think you were making this request of @JJendryka ; is that correct?
If so, know that I'm bringing your requested change in, as part of my outstanding PR.
(I know that's not completely correct, but I think it'll be okay this time, as I won't release until both of these are approved.)

2023-12-12 10:22 UTC, capn-freako approved these changes
Merging after thorough discussion w/ team.
All concerns addressed.
-db

2023-12-12 10:23 UTC, merged

2023-12-12 10:25 UTC, capn-freako commented
Thank you, all! :)

@JJendryka, would you like to have your head shot added to the _Faces of PyBERT_ collage?

@jdpatt , "LGTM"?

-db

2024-01-10 22:14 UTC, capn-freako commented
Hey guys,

I just had someone report that this broke importing Touchstone channel models for them.
And, sure enough, I was able to fix this person's problem by just reverting to GHz as the frequency unit.
Anyone know what's going on here?

Reviewing [their PR for this change](https://github.com/scikit-rf/scikit-rf/pull/935), it looks like they're planning to put this in v1.0.0.
Does anyone know whether or not it's in v0.30.0 (what I'm using)?
@JJendryka , might you have been compiling _SciKit-RF_ from (very current) source, as opposed to installing from _Conda_ or _PyPi_?

Thanks,
-db

2024-01-11 02:16 UTC, denzchoe commented
Hi @capn-freako ,

If we see the [touchstone.py file here](https://github.com/scikit-rf/scikit-rf/blob/af744d731d57d0994c72cb49db04a282eff51aeb/skrf/io/touchstone.py#L262C1-L266C46) & the Network [read_touchstone call here](https://github.com/scikit-rf/scikit-rf/blob/af744d731d57d0994c72cb49db04a282eff51aeb/skrf/network.py#L2195C1-L2197C60) ; 

if I interpret it correctly; the S-Parameters `frequency unit` gets passed to the Network Object regardless of the SI unit standardization. e.g.: If your Touchstone file  has the following header `# GHz S DB R 50.0 `, then the Network Object created will inherently carry the unit of GHz.

2024-01-13 15:09 UTC, capn-freako commented
Okay, never mind; there were just a few more places in the code where a `/1e9` had to be removed.

**==> Fixed in 6b708b9a4e9b117d4fccef358fcd866e38aba209.**